### ISSUE TITLE
cannot locate symbol "__android_log_write"

### ISSUE THREAD

**Issue by aferust** [adamdruppe/d_android#8]
Hi Adam,

I am playing around with the android thing. My generated *.so runs a SDL_main. My MainActivity derived from SDLActivity provided by the SDL2 android project. Just forget about the SDL thing and focus on the log functions. Those were some background.
```d
My d code is something like this:
import arsd.jni; // actually I use nothing from it
import android.ndk;

...
extern(System) export int SDL_main(int argc, char** argv) // invoked by SDLActivity thing
    {
       // when I comment __android_log_write lines, logcat says SDL_main is running from libmyapp.so
        __android_log_write(2, "com.example.basicactivity", "hmm starting");

        game = New!MyGame(1280, 720, false, "Dagon application", null);
        game.run(); // main loop

        __android_log_write(2, "com.example.basicactivity", "adios");
        
        return 0;
    }
...
```
I expect __android_log_write to work. When I run generated apk on my phone, I get this in logcat and in a modal msg win of the app:
System.err: dlopen failed: cannot locate symbol "__android_log_write" referenced by "/data/app/com.example.basicactivity-6GkdbYHnT2eG7AHUrBLa7A==/lib/arm64/libmyapp.so"

I see those definitions are in translated_headers/android/ndk. 

I know maybe it is hard to tell without more information. but, do I have to manually link something to address the missing symbol?

Thank you

**Comment by aferust** [comment]
I have tried linker entry "lflags": ["-llog"]. But it didn't work.

**Comment by aferust** [comment]
Ohh my bad. It must be defined in the build.gradle (:app). Now it works!

defaultConfig {
        applicationId "com.example.basicactivity"
        minSdkVersion 18
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        ndk {
            moduleName "armapi"
            ldLibs "log"
        }
    }

**Comment by adamdruppe** [comment]
ah good! yeah when you get one of those problems it is almost always a
library load thing. kinda awkward because android does these when it
runs rather than ahead of time when building, but the solution will
generally be to add it to that library link list.
